In [104]:
input_text = '국내 전반적인 경기침체로 상가 건물주의 수익도 전국적인 감소세를 보이고 있는 것으로 나타났다. 수익형 부동산 연구개발기업 상가정보연구소는 한국감정원 통계를 분석한 결과 전국 중대형 상가 순영업소득(부동산에서 발생하는 임대수입, 기타수입에서 제반 경비를 공제한 순소득)이 1분기 ㎡당 3만4200원에서 3분기 2만5800원으로 감소했다고 17일 밝혔다. 수도권, 세종시, 지방광역시에서 순영업소득이 가장 많이 감소한 지역은 3분기 1만3100원을 기록한 울산으로, 1분기 1만9100원 대비 31.4% 감소했다. 이어 대구(-27.7%), 서울(-26.9%), 광주(-24.9%), 부산(-23.5%), 세종(-23.4%), 대전(-21%), 경기(-19.2%), 인천(-18.5%) 순으로 감소했다. 지방 도시의 경우도 비슷했다. 경남의 3분기 순영업소득은 1만2800원으로 1분기 1만7400원 대비 26.4% 감소했으며 제주(-25.1%), 경북(-24.1%), 충남(-20.9%), 강원(-20.9%), 전남(-20.1%), 전북(-17%), 충북(-15.3%) 등도 감소세를 보였다. 조현택 상가정보연구소 연구원은 "올해 내수 경기의 침체된 분위기가 유지되며 상가, 오피스 등을 비롯한 수익형 부동산 시장의 분위기도 경직된 모습을 보였고 오피스텔, 지식산업센터 등의 수익형 부동산 공급도 증가해 공실의 위험도 늘었다"며 "실제 올 3분기 전국 중대형 상가 공실률은 11.5%를 기록하며 1분기 11.3% 대비 0.2% 포인트 증가했다"고 말했다. 그는 "최근 소셜커머스(SNS를 통한 전자상거래), 음식 배달 중개 애플리케이션, 중고 물품 거래 애플리케이션 등의 사용 증가로 오프라인 매장에 영향을 미쳤다"며 "향후 지역, 콘텐츠에 따른 상권 양극화 현상은 심화될 것으로 보인다"고 덧붙였다.'
input_text

'국내 전반적인 경기침체로 상가 건물주의 수익도 전국적인 감소세를 보이고 있는 것으로 나타났다. 수익형 부동산 연구개발기업 상가정보연구소는 한국감정원 통계를 분석한 결과 전국 중대형 상가 순영업소득(부동산에서 발생하는 임대수입, 기타수입에서 제반 경비를 공제한 순소득)이 1분기 ㎡당 3만4200원에서 3분기 2만5800원으로 감소했다고 17일 밝혔다. 수도권, 세종시, 지방광역시에서 순영업소득이 가장 많이 감소한 지역은 3분기 1만3100원을 기록한 울산으로, 1분기 1만9100원 대비 31.4% 감소했다. 이어 대구(-27.7%), 서울(-26.9%), 광주(-24.9%), 부산(-23.5%), 세종(-23.4%), 대전(-21%), 경기(-19.2%), 인천(-18.5%) 순으로 감소했다. 지방 도시의 경우도 비슷했다. 경남의 3분기 순영업소득은 1만2800원으로 1분기 1만7400원 대비 26.4% 감소했으며 제주(-25.1%), 경북(-24.1%), 충남(-20.9%), 강원(-20.9%), 전남(-20.1%), 전북(-17%), 충북(-15.3%) 등도 감소세를 보였다. 조현택 상가정보연구소 연구원은 "올해 내수 경기의 침체된 분위기가 유지되며 상가, 오피스 등을 비롯한 수익형 부동산 시장의 분위기도 경직된 모습을 보였고 오피스텔, 지식산업센터 등의 수익형 부동산 공급도 증가해 공실의 위험도 늘었다"며 "실제 올 3분기 전국 중대형 상가 공실률은 11.5%를 기록하며 1분기 11.3% 대비 0.2% 포인트 증가했다"고 말했다. 그는 "최근 소셜커머스(SNS를 통한 전자상거래), 음식 배달 중개 애플리케이션, 중고 물품 거래 애플리케이션 등의 사용 증가로 오프라인 매장에 영향을 미쳤다"며 "향후 지역, 콘텐츠에 따른 상권 양극화 현상은 심화될 것으로 보인다"고 덧붙였다.'

In [105]:
from transformers import BertTokenizerFast, BartForConditionalGeneration, BertModel, BertConfig, AutoModel, AutoTokenizer

tokenizer_bert = BertTokenizerFast.from_pretrained("kykim/bert-kor-base")
model_bert = BertModel.from_pretrained("kykim/bert-kor-base")

input_ids = tokenizer_bert.encode(input_text, return_tensors="pt")

with torch.no_grad():
    last_hidden_states = model_bert(input_ids)[0] # Models outputs are now tuples
print(last_hidden_states.shape)
print(last_hidden_states[0])

Some weights of the model checkpoint at kykim/bert-kor-base were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([1, 424, 768])
tensor([[ 0.3131,  0.1495, -0.2805,  ..., -1.0458,  0.2955,  0.2060],
        [-0.6040, -0.3774,  0.7601,  ..., -0.2936,  0.6367, -0.2034],
        [-0.9364, -0.4989,  1.5890,  ..., -0.1287,  0.1404,  0.0332],
        ...,
        [-0.7169,  0.1413,  1.1147,  ..., -1.0553,  0.1065, -0.3283],
        [ 0.0473, -0.1965,  0.2112,  ..., -1.1475, -0.5695,  0.0044],
        [ 0.2168,  0.0173, -0.6936,  ..., -0.9997, -0.1208,  0.1229]])


In [106]:
sentence_embeddings = last_hidden_states.mean(1)
print(sentence_embeddings)

tensor([[-1.1831e-01, -5.8520e-01,  2.8208e-01,  1.3134e-01, -5.3637e-01,
          6.4086e-02, -5.1276e-01, -7.0598e-01, -2.5589e-01, -2.9783e-01,
          1.0050e+00,  6.5010e-01, -3.2034e-01, -7.5098e-01, -6.5400e-01,
          1.5607e-01, -6.3496e-02, -4.9798e-01,  4.2883e-01,  4.3103e-01,
         -4.3904e-01, -6.6510e-01, -1.9600e-01,  1.4433e-01, -1.8935e-01,
          6.0381e-01, -8.4180e-01, -5.7096e-01, -4.5713e-02,  6.6888e-02,
          1.1719e+00,  2.8450e-01,  1.8008e-01,  8.2213e-01, -4.6427e-02,
          7.3754e-01, -1.2670e+00, -8.3744e-01,  1.9948e-01, -7.6356e-01,
         -8.1205e-02,  6.2777e-01,  7.7750e-01,  3.5418e-02, -5.1461e-01,
         -5.3380e-01, -3.3792e-02,  4.0549e-01, -1.2518e+00,  3.1446e-01,
         -1.0836e+00, -3.1691e-01,  5.0189e-02, -3.3321e-01, -5.1094e-01,
         -1.9821e-02, -6.3643e-01, -3.4611e-01,  4.1599e-01,  4.0669e-01,
         -5.9192e-01, -6.5608e-02, -4.9086e-01,  1.2308e-01, -6.3949e-01,
          3.4707e-01,  6.1347e-03, -1.

In [107]:
model = AutoModel.from_pretrained("kykim/bert-kor-base")
tokenizer = AutoTokenizer.from_pretrained("kykim/bert-kor-base")

# Transform input tokens 
inputs = tokenizer(input_text, return_tensors="pt")

# Model apply
outputs = model(**inputs)

outputs.last_hidden_state.shape
outputs.pooler_output.shape
outputs.keys()
print(outputs.last_hidden_state.shape)
print(outputs.last_hidden_state[0])

Some weights of the model checkpoint at kykim/bert-kor-base were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([1, 424, 768])
tensor([[ 0.3131,  0.1495, -0.2805,  ..., -1.0458,  0.2955,  0.2060],
        [-0.6040, -0.3774,  0.7601,  ..., -0.2936,  0.6367, -0.2034],
        [-0.9364, -0.4989,  1.5890,  ..., -0.1287,  0.1404,  0.0332],
        ...,
        [-0.7169,  0.1413,  1.1147,  ..., -1.0553,  0.1065, -0.3283],
        [ 0.0473, -0.1965,  0.2112,  ..., -1.1475, -0.5695,  0.0044],
        [ 0.2168,  0.0173, -0.6936,  ..., -0.9997, -0.1208,  0.1229]],
       grad_fn=<SelectBackward0>)


In [125]:
# https://huggingface.co/ainize/kobart-news
from transformers import PreTrainedTokenizerFast, BartForConditionalGeneration
#  Load Model and Tokenize
tokenizer = PreTrainedTokenizerFast.from_pretrained("ainize/kobart-news")
model = BartForConditionalGeneration.from_pretrained("ainize/kobart-news")

def summarize(model, tokenizer, input_text):
    input_ids = tokenizer.encode(input_text, return_tensors="pt")
    last_hidden_states = model(input_ids)[0]
    print('embeddings: ', last_hidden_states)
    print(last_hidden_states.shape)
    print('input ids: ', input_ids, len(input_ids[0]))
    # Generate Summary Text Ids
    output_ids = model.generate(
        input_ids=input_ids,
        bos_token_id=model.config.bos_token_id,
        eos_token_id=model.config.eos_token_id,
        length_penalty=2.0,
        max_length=142,
        min_length=56,
        num_beams=4,
    )
    print('output ids: ', output_ids[0], len(output_ids[0]))
    # Decoding Text
    return tokenizer.decode(output_ids[0], skip_special_tokens=True)

In [126]:
# Encode Input Text
input_text = '국내 전반적인 경기침체로 상가 건물주의 수익도 전국적인 감소세를 보이고 있는 것으로 나타났다. 수익형 부동산 연구개발기업 상가정보연구소는 한국감정원 통계를 분석한 결과 전국 중대형 상가 순영업소득(부동산에서 발생하는 임대수입, 기타수입에서 제반 경비를 공제한 순소득)이 1분기 ㎡당 3만4200원에서 3분기 2만5800원으로 감소했다고 17일 밝혔다. 수도권, 세종시, 지방광역시에서 순영업소득이 가장 많이 감소한 지역은 3분기 1만3100원을 기록한 울산으로, 1분기 1만9100원 대비 31.4% 감소했다. 이어 대구(-27.7%), 서울(-26.9%), 광주(-24.9%), 부산(-23.5%), 세종(-23.4%), 대전(-21%), 경기(-19.2%), 인천(-18.5%) 순으로 감소했다. 지방 도시의 경우도 비슷했다. 경남의 3분기 순영업소득은 1만2800원으로 1분기 1만7400원 대비 26.4% 감소했으며 제주(-25.1%), 경북(-24.1%), 충남(-20.9%), 강원(-20.9%), 전남(-20.1%), 전북(-17%), 충북(-15.3%) 등도 감소세를 보였다. 조현택 상가정보연구소 연구원은 "올해 내수 경기의 침체된 분위기가 유지되며 상가, 오피스 등을 비롯한 수익형 부동산 시장의 분위기도 경직된 모습을 보였고 오피스텔, 지식산업센터 등의 수익형 부동산 공급도 증가해 공실의 위험도 늘었다"며 "실제 올 3분기 전국 중대형 상가 공실률은 11.5%를 기록하며 1분기 11.3% 대비 0.2% 포인트 증가했다"고 말했다. 그는 "최근 소셜커머스(SNS를 통한 전자상거래), 음식 배달 중개 애플리케이션, 중고 물품 거래 애플리케이션 등의 사용 증가로 오프라인 매장에 영향을 미쳤다"며 "향후 지역, 콘텐츠에 따른 상권 양극화 현상은 심화될 것으로 보인다"고 덧붙였다.'
decoded_text = summarize(model, tokenizer, input_text)
print(decoded_text)

embeddings:  tensor([[[ 31.6866,   9.3366,  11.2337,  ...,   4.5137,   7.3841,   7.1725],
         [ -2.3933,   2.1697,  -7.8838,  ...,  -7.2838,  -9.8763,  -5.3370],
         [ -4.9029,  -0.6490,  -9.7926,  ...,  -8.6843, -15.5855,  -8.3866],
         ...,
         [ -1.7835,   2.1035,  -2.8559,  ...,  -4.8765,  -3.2337,  -3.6935],
         [ -2.4649,   5.5784,  -1.4122,  ...,  -4.5981,  -0.9677,  -4.7450],
         [ -4.5541,  16.5802,  -7.4921,  ...,  -5.8620,  -9.5876, -11.4848]]],
       grad_fn=<AddBackward0>)
torch.Size([1, 365, 30000])
input ids:  tensor([[    0, 23436, 25623, 27091, 21067, 23895, 16442, 14453, 15342,  9866,
         14770, 14134, 15665, 14896, 16553, 14082, 14173, 19743, 14130, 15342,
         13679, 15821, 22164, 14451, 23895, 15107, 14867, 17047, 14188,  8995,
         22036, 14109, 15161, 22269, 14494, 14770, 22537, 13679, 23895, 14408,
         18801, 16162,   239, 23625, 14030, 19668, 17249, 22540,   243, 18453,
         22540, 14030, 14060, 10773, 14051,

In [103]:
# Encode Input Text
input_text = "미국의 안경 및 콘택트 렌즈, 선글라스 등 판매업체 와비 파커의 2분기 주당순손실은 0.01달러로 월가의 예상치 0.02달러에 하회한 것으로 나타났다. 11일(현지시간) 와비 파커에 따르면 이 기간 매출은 1억4,960만달러로 시장 예상치 1억4,950만달러에는 약간 상회했다. 스티브 밀러 최고재무책임자(CFO)는 우리는 대부분의 기업들과 마찬가지로 불확실한 거시경제 환경에 직면하고 있다며 올들어 매출 부진이 이어져 손실이 확대되고 있고, 이에 올해 매출 전망도 대폭 하향 조정한다고 밝혔다"
decoded_text = summarize(model, tokenizer, input_text)
print(decoded_text)

미국국의 안경 및 콘택트 렌즈, 선글라스 등 판매업체 와비 파커의 2분기 주당순손실은 0.01달러로 월가의 예상치 0.02달러에 하회했으며 이 기간 매출은 1억4,960만달러로 시장 예상치에는 약간 상회한 것으로 나타났고 올해 매출 전망도 대폭 하향 조정한다고 밝혔다.


In [124]:
input_text = """
[서울=뉴시스] 최현호 기자 = 한국거래소는 22일 주권상장 예비심사 결과, 컬리가 상장요건을 충족해 상장에 적격한 것으로 확정했다고 밝혔다.

온라인 장보기앱 마켓컬리 운영사인 컬리는 지난 3월 말 한국거래소에 상장 심사를 신청했다. 약 5개월 만에 심사를 통과한 것이다.

컬리의 별도 기준 지난해 매출액은 1조 5580억원, 영업손실은 2139억원이다.

2014년 설립된 컬리는 새벽배송 등 전자상거래 소매업을 영위하는 회사다.

컬리의 주요 주주는 미국 세콰이어캐피탈(12.87%), 중국계 힐하우스캐피탈(11.89%), 러시아계 디지털스카이테크놀로지글로벌(10.17%)과 올해 주주로 합류한 앵커에쿼티파트너스 등이다.
"""
decoded_text = summarize(model, tokenizer, input_text)
print(input_text)
print(decoded_text)

torch.Size([1, 156, 30000])
input ids:  tensor([[    0,   230,   290, 17303, 17515,   292, 14099, 13672, 13699, 14680,
         15146, 27070, 17047, 16670, 14053,  9190, 11224, 12074, 16817, 20050,
         19571, 18556, 14493, 17817, 11900, 16000, 20205, 13607, 14066, 15068,
         14184, 19618, 14173, 16053, 14781, 14278,   230, 25845, 14137, 18837,
         11729, 14087, 12943, 12926, 10476, 14585, 17547, 18556, 14298, 14141,
         15459, 14070, 27070, 16755, 17817, 25917, 15453, 15615, 14383, 28319,
         15322, 25917, 16342, 13590, 14237,   230, 12926, 15470, 24813, 14832,
         14437, 15240, 17449, 17848, 19479, 17918, 18865, 15249, 11323, 19822,
         16167, 26055, 14395, 14052,   230, 15546, 15178, 27744, 18556, 14298,
         17412, 10795, 11331, 14048, 16246, 11224, 15471, 24563, 15385, 14126,
         11973, 14049, 15454, 14024,   230, 12926, 15470, 14979, 14053, 14785,
         14287, 14115, 12984, 15740, 25162, 28080, 16030,   254, 18056, 14361,
          90